/**
 * This file was generated by the Jeddict
 */
package educationproject.entities;

import javax.persistence.*;

/**
 * @author Jakob
 */
@Entity
@IdClass(GradePK.class)
public class Grade {

    @Basic
    @Column(name = "gradeString")
    private String level;

    @Id
    @ManyToOne
    private Student student;

    @Id
    @ManyToOne
    private Course course;

    public Grade(Student student, Course course, String level) {
        this.student = student;
        this.course = course;
        this.level = level;
    }

    public Grade() {
    }
    
    

    public String getLevel() {
        return this.level;
    }

    public void setLevel(String level) {
        this.level = level;
    }

    public Student getStudent() {
        return this.student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    public Course getCourse() {
        return this.course;
    }

    public void setCourse(Course course) {
        this.course = course;
    }
    
    public String toString(){
        return String.format("%20s - %20s (%s)",student.getName(), course.getName(), level);
    }

}