//
// This file was generated by the Jeddict
//
package educationproject.entities;

import java.io.Serializable;
import java.util.Objects;

public class GradePK implements Serializable {

    private int student;

    private int course;

    public GradePK() {
    }

    public GradePK(int student, int course) {
        this.student = student;
        this.course = course;
    }

    public long getStudent() {
        return this.student;
    }

    public void setStudent(int student) {
        this.student = student;
    }

    public int getCourse() {
        return this.course;
    }

    public void setCourse(int course) {
        this.course = course;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final GradePK other = (GradePK) obj;
        if (!java.util.Objects.equals(this.getStudent(), other.getStudent())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getCourse(), other.getCourse())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(this.getStudent());
        hash = 31 * hash + Objects.hashCode(this.getCourse());
        return hash;
    }

    @Override
    public String toString() {
        return "GradePK{" + " student=" + student + ", course=" + course + '}';
    }

}